### ISSUE TITLE
About mjrl_envs

### ISSUE THREAD

**Issue by lzl60109** [vikashplus/robohive#104]
Has the mjrl_envs package been renamed?I came in from someone else's link and found I couldn't find the package name

**Comment by vikashplus** [comment]
Yes. it's has been renamed as RoboHive. 
- All versions of the repo are available as pre-releases (https://github.com/vikashplus/robohive/releases). If you are look for the original mj_envs repo with the DAPG paper the release tag will be v0.0
- Do let us know if there are any stale links on web pages that we can update.
