### ISSUE TITLE
MuJoCo installation issues on MacBook 

### ISSUE THREAD

**Issue by Alpslee** [vikashplus/robohive#114]
note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for mujoco
  Running setup.py clean for mujoco
Failed to build mujoco
ERROR: Could not build wheels for mujoco, which is required to install pyproject.toml-based projects

**Comment by vikashplus** [comment]
@Alpslee  Can you please provide some details about 
- your OS 
- your machine details
- version of RoboHive you are trying to install 
- version of MuJoCo that is failing

**Comment by vikashplus** [comment]
Try the fix suggested here - https://github.com/google-deepmind/mujoco/issues/1004
