### ISSUE TITLE
Deformable object simulation support in RoboHive

### ISSUE THREAD

**Issue by TheGoblinTechies** [vikashplus/robohive#117]
Thanks for the authors' hard work building a comprehensive simulation environment based on MuJoCo. I noticed that deformable object simulation is already implemented from the demo figures, but I couldn't find the exact environment. Would you happen to know when the relevant code of deformable object simulation will be released? Much thanks.

**Comment by vikashplus** [comment]
It's already implemented from a simulation and environment point of view. We do not have trained policies, or polished observation and rewards spaces. Please let us if this will still be of use and if you are actively planning to use them. We can boost the priority and work together with you to post it to the next release.
