### ISSUE TITLE
Could you please upload the data set to huggingface? Google drive may have problems when downloading files with large size of data. Thank you very much.

### ISSUE THREAD

**Issue by happyflying-web** [vikashplus/robohive#121]
Could you please upload the data set to huggingface? Google drive may have problems when downloading files with large size of data. Thank you very much.

**Comment by vikashplus** [comment]
@gaoyuezhou @Jdvakil  -- What do you guys think?

**Comment by happyflying-web** [comment]
Thank you for considering my proposal, because when using Google Drive to download the data set, the files in the folder are always incompletely downloaded, and some files are lost. When I tried to find a solution online, I found that many people had encountered this problem.

**Comment by vikashplus** [comment]
@happyflying-web -- do you have experience working with Huggingface? Wil it satisfy yours requests?

**Comment by happyflying-web** [comment]
Thank you for your reply. I have used huggingface before, and it should be able to meet the download requests. Of course, it only provides a way. You can also upload other available places for downloading. The main reason is that Google Drive performs remote packaging and compression before downloading, so there will always be file loss after downloading the compressed file especially when the file size very large. Thanks again!

**Comment by Jdvakil** [comment]
@happyflying-web We have uploaded the dataset here -- https://huggingface.co/datasets/jdvakil/RoboSet_Sim

**Comment by happyflying-web** [comment]
Thank you for your contribution！
