### ISSUE TITLE
Request for support for xArm Series arm

### ISSUE THREAD

**Issue by MARMOTatZJU** [vikashplus/robohive#127]
Hello, many thanks for this solid work!

I would like to hear about your further plans that are related to the support for new robot arms, especially for [xArm series](https://www.ufactory.cc/xarm-collaborative-robot/) constructed by uFactory.

Awaiting your reply and thanks in advance!

**Comment by vikashplus** [comment]
Hi @MARMOTatZJU  
Thanks for your interest in RoboHive. Expanding the robot and task collections is in RoboHive's roadmap. However, we don't have any active thread for XArm as of now.

Adding a new arm should be quite straightforward. I'd be happy to help if you want to work together on a PR and get it merged. Let me know.

**Comment by MARMOTatZJU** [comment]
@vikashplus Sure, many thanks again for your reply!

I am considering conducting research on fine manipulation with xArm, and I am evaluating the feasibility of doing it with RoboHive (using it as our simulator)!

At this moment, I would like to know those quintessential steps that are required for the implementation of a new arm within RoboHive.

**Comment by vikashplus** [comment]
1. Add xarm sim to [simhive](https://github.com/vikashplus/robohive/tree/main/robohive/simhive). MuJoCo Menagerie has a [xarm-model](https://github.com/google-deepmind/mujoco_menagerie/tree/main/ufactory_xarm7) that we can use.
2. Create a config file to specify the hardware limit. [Here is an example you can copy paste](https://github.com/vikashplus/robohive/blob/main/robohive/envs/arms/fetch/assets/fetch_reach_v0.config). You can also skip this step and RoboHive will create a default one for you 
3. Register a new env ([copy paste these lines](https://github.com/vikashplus/robohive/blob/main/robohive/envs/arms/__init__.py#L19-L30)) with paths to the new sim and the config(if created)

**Comment by MARMOTatZJU** [comment]
> 1. Add xarm sim to [simhive](https://github.com/vikashplus/robohive/tree/main/robohive/simhive). MuJoCo Menagerie has a [xarm-model](https://github.com/google-deepmind/mujoco_menagerie/tree/main/ufactory_xarm7) that we can use.
> 2. Create a config file to specify the hardware limit. [Here is an example you can copy paste](https://github.com/vikashplus/robohive/blob/main/robohive/envs/arms/fetch/assets/fetch_reach_v0.config). You can also skip this step and RoboHive will create a default one for you
> 3. Register a new env ([copy paste these lines](https://github.com/vikashplus/robohive/blob/main/robohive/envs/arms/__init__.py#L19-L30)) with paths to the new sim and the config(if created)

Thank you very much for this guidance! We will try to integrate xArm models into RoboHive and will consider create a PR after verification of the function.

I thereby close this issue. I will reopen it if we encounter any issue that worths further discussion.

Thank you again!
