### ISSUE TITLE
Resetting robot during env setup

### ISSUE THREAD

**Issue by andrearosasco** [vikashplus/robohive#131]
I found this line in env_base.MujocoEnv._setup
       
```python
observation, _reward, done, _info = self.step(np.zeros(self.sim.model.nu))
# Question: Should we replace above with following? Its specially helpful for hardware as it forces a env reset before continuing, without which the hardware will make a big jump from its position to the position asked by step.
# observation = self.reset()
```

Since on the real robot the requested position causes an overcurrent, I commented the line and de-commented `observation = self.reset()`

I wonder, since it wasn't de-commented already, can it cause any issue?

**Comment by vikashplus** [comment]
When working with hardware,  for safety `observation = self.reset()`should be called before calling any step function. Your intuition here is correct and I don't envision any issues.

**Comment by vikashplus** [comment]
In our usecase (with hardware)
- reset are much longer than step 
- step at the launch is stable (so there was no real need for reset) 
So it was a bit more optimal for our hardware
