### ISSUE TITLE
Rendered depth is upside down

### ISSUE THREAD

**Issue by sriramsk1999** [vikashplus/robohive#132]
Hello,

Thanks for the great work on RoboHive. I am observing a strange issue - the depth rendered by RoboHive is flipped upside down. The issue exists for all 4 cams (wrist, left, right, top) as well as other environments used directly through RoboHive or through torchRL's `RoboHiveEnv`.

Minimal example:
```py
import gym
import robohive
import matplotlib.pyplot as plt
import numpy as np

env = gym.make("rpFrankaRobotiqData-v0")
env.reset()

extero_dict = env.get_exteroception()

rgb = extero_dict["rgb:left_cam:240x424:2d"]
dep = extero_dict["d:left_cam:240x424:2d"].squeeze()

plt.imsave("rgb.png", rgb)
plt.imsave("depth.png", dep)  ### Vertically flipped ###
plt.imsave("depth_flipped.png", np.flipud(dep))  ### Works ###
```

The corresponding images:
1. `rgb.png`
![rgb](https://github.com/vikashplus/robohive/assets/19668051/443afbe7-b949-4d14-9a21-09b5a9e063cf)
2. `depth.png`
![depth](https://github.com/vikashplus/robohive/assets/19668051/22a6bf8f-fd90-4440-b9f3-3c0314ec6fd1)
3. `depth_flipped.png`
![depth_flipped](https://github.com/vikashplus/robohive/assets/19668051/a03532db-d5e0-40d9-92e2-cff38c37305d)

**Comment by vikashplus** [comment]
Glad you are enjoying working with RoboHive. 
To the best of my memory, we had to explicitly flip the buffer returned by the MuJoCo's python wrapper as it was upside down ([see details here](https://github.com/vikashplus/robohive/blob/main/robohive/renderer/mj_renderer.py#L117)) It might be the case that the new wrapper doesn't require this explicit flipping. 

It will be great if you can play around with it and send a PR if this is the case.

**Comment by vikashplus** [comment]
Once you have checked this details, please send a PR. 
CC @Jdvakil

**Comment by sriramsk1999** [comment]
Raised a PR to the dev branch. However, on the `dev` branch, the rendered depth is no longer in metres. It appears to have been scaled down, with the min/max values being 0.03500000387430191 and 0.03606634587049484. Not sure if this is expected behaviour.

**Comment by vikashplus** [comment]
Can you point me to the lines where you observe the mentioned scaling?

**Comment by sriramsk1999** [comment]
Fixed it :) The change introduced [here](https://github.com/vikashplus/robohive/commit/ae51c9e158c4cc6643cc7470e6979fa92408f873) setting the depth mapping method to `mjDEPTH_ZERONEAR` is causing the issue.

After removing this line, I get standard depth in metres. I am not getting any warnings either. What do you suggest?

**Comment by vikashplus** [comment]
Ah, yeah. I made that fix when Mujoco was a bit unstable on it. Can you send a PR for that? I'll text it again and accept the PR for the next release.

**Comment by sriramsk1999** [comment]
Gentle bump on this :) Please let me know if there's anything to be done from my side to get the PRs merged.

**Comment by vikashplus** [comment]
Thanks for the bump. All changes have been merged.
