### ISSUE TITLE
Creating a bright colored LED-like object ?

### ISSUE THREAD

**Issue by dosssman** [vikashplus/robohive#145]
Hello everyone.
Thanks a lot for your answer on Twitter @vikashplus . Opening in issue as you suggested.

I am currently working with the Franka arms environment for pick and place.
I am trying to create an object looking like a moderately bright LED.
For example, the blue status LED at the base of the Franka robotics Arm, like the screenshot below.

So far I have played with the light from the [docs](https://mujoco.readthedocs.io/en/stable/XMLreference.html#body-light) but it seems to only support general room lighting.

Another thing I tried was the [lightButton](https://github.com/vikashplus/furniture_sim/tree/master/lightButtons) from furniture_sim repository, but the "light effect" has neither _reflection nor _shininess_-like properties.

Is perhaps another way to achieve the aforementioned desired effect ?
Or more generally, an object that is emitting light itself ?

Thanks a lot for your continued assistance.
Looking forward to hear from you again.
Best regards.

![image](https://github.com/vikashplus/robohive/assets/21224272/dca5e223-a086-4c0d-a9c8-e7c00c2179d6)

PS: Also asked this at the Mujoco repository: https://github.com/google-deepmind/mujoco/issues/1626

**Comment by vikashplus** [comment]
Closest to what you are asking can be achieved by
1. creating a geom in the shape of the light 
2. changing the `rgba=".5 .5 10 1"` when you want to turn it on

**Comment by dosssman** [comment]
Thanks a lot !
Definitely going to be of some help.
