### ISSUE TITLE
Issues Reproducing DAPG Training with RoboHive on Mujoco Version Greater than 210

### ISSUE THREAD

**Issue by binbinbai** [vikashplus/robohive#150]
Hi, I'm a student working on dexterous hand manipulation research, and I have some questions. I’m trying to reproduce the DAPG training process as an exercise using Mujoco versions greater than 210 within the RoboHive framework, but I’ve encountered a few issues.

It seems that the mj_envs from DAPG is now integrated into robohive/envs/hands, is that correct? Additionally, the important MujocoEnv(gym.Env) class from mjrl appears to have been moved to robohive/envs/hands/env_base.py. In this case, how should I go about using the various algorithms provided in mjrl?

Lastly, is it possible to reproduce DAPG on newer Mujoco versions without relying on mujoco_py?

Thanks for any advice!

**Comment by vikashplus** [comment]
This is correct - `mj_envs` are now `robohive`. You can see the updated envs [here](https://github.com/vikashplus/robohive/blob/main/robohive/envs/hands/__init__.py)

These envs are now independent of `mjrl` dependencies. You should be able to use any Agent's framework that supports Gym-API. 

We also release a good collection of trained agents that you can use as examples - https://sites.google.com/view/robohive/baseline?authuser=0
