### ISSUE TITLE
dependencies missing

### ISSUE THREAD

**Issue by Vittorio-Caggiano** [vikashplus/robohive#18]
the following dependencies are missing from a clean install:
- transforms3d
- pydantic
- mjrl

**Comment by vikashplus** [comment]
- flatten_dict

**Comment by tattrongvu** [comment]
Hi, I'm trying to reproduce the result from VIP paper, so i follow the instruction in your git but when i import relay_kitchen it say missing 'mjrl'. Could you provide more instruction to install this module and how to use this properly. Thanks in advance!

**Comment by vikashplus** [comment]
We revamped the installation/deploy strategy in `v0.5`. 
(Though this issue was resolved much before that)
