### ISSUE TITLE
Not able to visualize the environment on AWS EC2

### ISSUE THREAD

**Issue by anilsh** [vikashplus/robohive#24]
I am able to run the `utils/visualize_env.py` in the terminal and it is returning the score for 10 episodes. But it is not showing the actual visualization.

Any suggestions?

I am using `xvfb-run bash` to get the above said output. Otherwise, it returns libGLEW error.

**Comment by vikashplus** [comment]
Please use offscreen rendering for remote operations. 
`utils/visualize_env.py -e <env_name> -r offscreen`
