### ISSUE TITLE
What's the best way to train/deploy policy in Robohive?

### ISSUE THREAD

**Issue by vikashplus** [vikashplus/robohive#83]
What's the best way policy trained outside robohive and want to evaluate in robohive? 

A policy with state inputs
```
class StatePolicy:
    def __init__(self, env):
        self.env=env
    def get_action(self, obs_state):
        action = self.policy(obs_state)
        return action, action
```

A policy with custom visual inputs
```
class VisualPolicy:
    def __init__(self,env, user_encoder):
        self.env=env
        self.user_encoder=user_encoder
    def get_action(self, obs_state):
        prop_feat = self.env.get_proprio()
        img_feat = self.env.get_extero()
        feature = user_encoder(prop_feat, img_feat)
        action = self.policy(feature)
        return action, action
```

by @0wu

**Comment by vikashplus** [comment]
Docs/ tutorial will be great for this.

**Comment by mrshetab** [comment]
@vikashplus Thank you for explaining how to test a policy that is trained outside robohive.
Would you please, explain also how to train a model using robohive. For example, how to use it along with stable-baseline3 to train an agent using rl. In stable-baseline, we use the function model.learn() to interact directly with the env. This means that it uses observations coming from env directly.  How we can use images coming from one camera as the observation?
Thank you in advance

**Comment by vikashplus** [comment]
You need to be on the dev branch to use stale baselines for now (I'll merge to the main soon) 
 
 Here are two examples that can be helpful 
- https://github.com/vikashplus/robohive/blob/dev/robohive/tests/test_sb.py 
- Check the colab lined with the readMe of the repo for another example - https://colab.research.google.com/drive/1rdSgnsfUaE-eFLjAkFHeqfUWzAK8ruTs?usp=sharing
