### ISSUE TITLE
R3M Franka Kitchen Environments / Demonstration Data

### ISSUE THREAD

**Issue by siddk** [vikashplus/robohive#90]
Hey @vikashplus! This is an awesome effort, and I'd love to help out if I can! I'm looking for a clean way to integrate the R3M Franka Kitchen and Adroit HMS evaluations into the Voltron Evaluation repository (https://github.com/siddk/voltron-evaluation), and I think that using Robohive as a dependency instead of the R3M Evaluation branch (+ corresponding forked submodules) makes the most sense.

From the docs though, it's not clear which environments/dataset is the right one to use; for the evaluations we ran in the Voltron work (https://arxiv.org/abs/2302.12766) we followed the same setup as R3M, evaluating 3 camera angles at 5, 10, and 25 demonstrations for each of the 5 tasks (with 50 heldout environments for validation). Should I be using the `v3` or `v4` environments? And how should I specify the three camera angles (`left_cap2`, `right_cap2`, `default`)?

Thanks so much - and if there's anything I can help out with to incorporate the changes to setup this eval, please let me know!

**Comment by siddk** [comment]
Hey @vikashplus - thank you so much for this! Really appreciate the links, and I'm going to try replicating the "R3M evaluation" flow with the `v3` environments for now, and PR to the `voltron-evaluation` repository in the next week (and maybe even get our newer/more powerful Voltron models + other baselines added to the page you linked above).

In general, would love to connect in-person or over Zoom and actually talk about coming up with a holistic evaluation suite, maybe even starting a collaboration to combine + extend both our efforts! Lots of cool work in this space, and I'd love to get critical mass!

**Comment by vikashplus** [comment]
Hi @siddk 
1. If you are interested in perfect R3M evals as reported in the paper, I'd recommend using the [R3M checkpoint/tag from here](https://github.com/vikashplus/robohive/releases/tag/v0.0.5)
2. My recommendation will be use the [upgraded envs](https://github.com/vikashplus/robohive/blob/main/robohive/envs/multi_task/substeps1/franka_kitchen.py), [datasets](https://github.com/vikashplus/robohive/wiki/7.-Datasets), and [baselines](https://sites.google.com/view/robohive/baseline?authuser=0) for more rigorous evals and for being future safe.

**Comment by vikashplus** [comment]
Closing this issue. Please let us know if we can provide further details.
