### ISSUE TITLE
Issuses from mujoco_py/mujoco

### ISSUE THREAD

**Issue by lzhhh93** [vikashplus/robohive#93]
Following using `pip install robohive` on Windows 11 running an Ubuntu 20.04 (64-bit) VM. I run into a lot of problems coming up on my side. When I run the demo, something is always off in this step:

![image](https://user-images.githubusercontent.com/38736831/236168413-c9beee3d-9c19-46a8-bb86-d322f08f58ca.png)

Since many issues related to `mujoco_py`, I have got a lot of them solved by installing mujoco-py before installing robohive, following answers from the side of mujoco_py repo like https://github.com/openai/mujoco-py/issues/284. However, now I seem stuck in here:

![image](https://user-images.githubusercontent.com/38736831/236168980-c919ff6f-ff44-4211-bf09-c05f836f5f17.png)

,which can only be solved by build Mujoco from source with modification according to them https://github.com/openai/mujoco-py/issues/737 and https://github.com/deepmind/mujoco/issues/849. And yet I am still waiting for clear instruction from them. 

So I am concerned about whether I am on the right track, since it may take another amount of time.

I appreciate for any advice.

**Comment by lzhhh93** [comment]
According to https://github.com/deepmind/mujoco/issues/849, it seems that building Mujoco from source does not work for Mujoco 2.1.0 which is the newest version that is compatible with `mujoco-py`.

**Comment by vikashplus** [comment]
@lzhhh93 - Im sorry about this. Getting MuJoCo_py installation on windows has always been quite challenging. It's unfortunately outside the scope of support we can provide from RoboHive's team. We would still like to provide as much help we possibly can - 

We have a sister project [MyoSuite](https://sites.google.com/view/myosuite) where folks have had some success getting MuJoCo_Py installed on windows via VM. You can follow the [thread here](https://github.com/facebookresearch/myosuite/issues/14)

**Comment by vikashplus** [comment]
I'm closing this issue. Please reopen the issue if we there are further helps we can provide on RoboHive.
