### ISSUE TITLE
Error in "Explore Robots" session in tutorial

### ISSUE THREAD

**Issue by lzhhh93** [vikashplus/robohive#94]
Hi,

I try to follow the tutorial here https://github.com/vikashplus/robohive/wiki/6.-Tutorials-&-FAQs#explore-robots, but it shows the error below which seems confusing:

![get_sim problem](https://github.com/vikashplus/robohive/assets/38736831/b1b92faa-ac39-4e26-a37d-df2f51925cc5)

Thanks in advance!

**Comment by vikashplus** [comment]
Thanks for catching the bug. I have resolved the bug 65d129b7b150b4c72f0e119dfaf105bc7d32caf9. It will be a part of the next release which is slated in roughly 2 weeks.

Thanks for your interest in RoboHive.
